import type { RawMayangoliWord } from './wordEntry'

// Verified Mayangoli word bank -- 315 words sourced from a teacher-
// curated spreadsheet (Tamizhi_Mayangoli_315_Word_Bank.xlsx), parsed
// and validated programmatically: every entry's targetLetter was
// confirmed to actually occur in its word via Intl.Segmenter grapheme
// splitting (see graphemes.ts), and every distractor was confirmed to
// be a real Mayangoli-relevant consonant grapheme distinct from the
// correct answer. reviewStatus is 'generated' for every entry per the
// explicit rule that processing/validating data programmatically is
// NOT the same as a human teacher reviewing it for correctness --
// promoting entries to 'reviewed'/'approved' happens through the
// teacher-facing question bank admin screen, not here.
export const MAYANGOLI_WORDS: RawMayangoliWord[] = [
  {
    id: 'mayangoli_001',
    word: 'மலை',
    targetLetter: 'ல',
    difficulty: 'easy',
    meaningEnglish: 'mountain',
    meaningTamil: 'உயர்ந்த நிலப்பகுதி',
    distractors: ['ளை', 'ழை'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_002',
    word: 'இலை',
    targetLetter: 'ல',
    difficulty: 'easy',
    meaningEnglish: 'leaf',
    meaningTamil: 'தாவரத்தின் பச்சைப் பகுதி',
    distractors: ['ளை', 'ழை'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_003',
    word: 'வலை',
    targetLetter: 'ல',
    difficulty: 'easy',
    meaningEnglish: 'net',
    meaningTamil: 'பிடிக்கப் பயன்படும் பின்னல்',
    distractors: ['ளை', 'ழை'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_004',
    word: 'அலை',
    targetLetter: 'ல',
    difficulty: 'easy',
    meaningEnglish: 'wave',
    meaningTamil: 'கடல் நீரின் எழுச்சி',
    distractors: ['ளை', 'ழை'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_005',
    word: 'கலை',
    targetLetter: 'ல',
    difficulty: 'easy',
    meaningEnglish: 'art',
    meaningTamil: 'படைப்புத் திறன்',
    distractors: ['ளை', 'ழை'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_006',
    word: 'தலை',
    targetLetter: 'ல',
    difficulty: 'easy',
    meaningEnglish: 'head',
    meaningTamil: 'உடலின் மேற்பகுதி',
    distractors: ['ளை', 'ழை'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_007',
    word: 'நிலை',
    targetLetter: 'ல',
    difficulty: 'easy',
    meaningEnglish: 'state / condition',
    meaningTamil: 'நிற்கும் தன்மை / சூழ்நிலை',
    distractors: ['ளை', 'ழை'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_008',
    word: 'விலை',
    targetLetter: 'ல',
    difficulty: 'easy',
    meaningEnglish: 'price',
    meaningTamil: 'பொருளின் மதிப்பு',
    distractors: ['ளை', 'ழை'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_009',
    word: 'சிலை',
    targetLetter: 'ல',
    difficulty: 'easy',
    meaningEnglish: 'statue',
    meaningTamil: 'செதுக்கப்பட்ட உருவம்',
    distractors: ['ளை', 'ழை'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_010',
    word: 'காலை',
    targetLetter: 'ல',
    difficulty: 'easy',
    meaningEnglish: 'morning',
    meaningTamil: 'நாளின் தொடக்க நேரம்',
    distractors: ['ளை', 'ழை'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_011',
    word: 'மாலை',
    targetLetter: 'ல',
    difficulty: 'easy',
    meaningEnglish: 'evening / garland',
    meaningTamil: 'சாயங்காலம் / பூமாலை',
    distractors: ['ளை', 'ழை'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_012',
    word: 'வேலை',
    targetLetter: 'ல',
    difficulty: 'easy',
    meaningEnglish: 'work',
    meaningTamil: 'தொழில் / பணி',
    distractors: ['ளை', 'ழை'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_013',
    word: 'சாலை',
    targetLetter: 'ல',
    difficulty: 'easy',
    meaningEnglish: 'road',
    meaningTamil: 'பயணப் பாதை',
    distractors: ['ளை', 'ழை'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_014',
    word: 'பாலை',
    targetLetter: 'ல',
    difficulty: 'medium',
    meaningEnglish: 'arid land',
    meaningTamil: 'ஒரு திணை / வறண்ட நிலம்',
    distractors: ['ளை', 'ழை'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_015',
    word: 'பால்',
    targetLetter: 'ல',
    difficulty: 'easy',
    meaningEnglish: 'milk',
    meaningTamil: 'பால் பானம்',
    distractors: ['ள்', 'ழ்'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_016',
    word: 'கால்',
    targetLetter: 'ல',
    difficulty: 'easy',
    meaningEnglish: 'leg',
    meaningTamil: 'உடல் உறுப்பு',
    distractors: ['ள்', 'ழ்'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_017',
    word: 'வால்',
    targetLetter: 'ல',
    difficulty: 'easy',
    meaningEnglish: 'tail',
    meaningTamil: 'விலங்கின் பின்புற உறுப்பு',
    distractors: ['ள்', 'ழ்'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_018',
    word: 'நூல்',
    targetLetter: 'ல',
    difficulty: 'easy',
    meaningEnglish: 'book / thread',
    meaningTamil: 'புத்தகம் / இழை',
    distractors: ['ள்', 'ழ்'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_019',
    word: 'வேல்',
    targetLetter: 'ல',
    difficulty: 'medium',
    meaningEnglish: 'spear',
    meaningTamil: 'ஈட்டி போன்ற ஆயுதம்',
    distractors: ['ள்', 'ழ்'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_020',
    word: 'மேல்',
    targetLetter: 'ல',
    difficulty: 'easy',
    meaningEnglish: 'above',
    meaningTamil: 'உயர்ந்த பக்கம்',
    distractors: ['ள்', 'ழ்'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_021',
    word: 'நீலம்',
    targetLetter: 'ல',
    difficulty: 'easy',
    meaningEnglish: 'blue',
    meaningTamil: 'நீல நிறம்',
    distractors: ['ள', 'ழ'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_022',
    word: 'உலகம்',
    targetLetter: 'ல',
    difficulty: 'easy',
    meaningEnglish: 'world',
    meaningTamil: 'பூமி / உலகம்',
    distractors: ['ள', 'ழ'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_023',
    word: 'கலகம்',
    targetLetter: 'ல',
    difficulty: 'medium',
    meaningEnglish: 'disturbance',
    meaningTamil: 'குழப்பம் / மோதல்',
    distractors: ['ள', 'ழ'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_024',
    word: 'கலவை',
    targetLetter: 'ல',
    difficulty: 'medium',
    meaningEnglish: 'mixture',
    meaningTamil: 'பலவற்றின் சேர்க்கை',
    distractors: ['ள', 'ழ'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_025',
    word: 'நிலவு',
    targetLetter: 'ல',
    difficulty: 'easy',
    meaningEnglish: 'moon',
    meaningTamil: 'சந்திரன்',
    distractors: ['ள', 'ழ'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_026',
    word: 'நிலம்',
    targetLetter: 'ல',
    difficulty: 'easy',
    meaningEnglish: 'land',
    meaningTamil: 'தரை / பூமி',
    distractors: ['ள', 'ழ'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_027',
    word: 'பலன்',
    targetLetter: 'ல',
    difficulty: 'medium',
    meaningEnglish: 'result / benefit',
    meaningTamil: 'விளைவு / பயன்',
    distractors: ['ள', 'ழ'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_028',
    word: 'பலம்',
    targetLetter: 'ல',
    difficulty: 'easy',
    meaningEnglish: 'strength',
    meaningTamil: 'வலிமை',
    distractors: ['ள', 'ழ'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_029',
    word: 'வலம்',
    targetLetter: 'ல',
    difficulty: 'medium',
    meaningEnglish: 'going around / right side',
    meaningTamil: 'சுற்றிச் செல்லுதல் / வலப்பக்கம்',
    distractors: ['ள', 'ழ'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_030',
    word: 'விலங்கு',
    targetLetter: 'ல',
    difficulty: 'easy',
    meaningEnglish: 'animal',
    meaningTamil: 'உயிரின வகை',
    distractors: ['ள', 'ழ'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_031',
    word: 'இலங்கை',
    targetLetter: 'ல',
    difficulty: 'easy',
    meaningEnglish: 'Sri Lanka',
    meaningTamil: 'ஒரு தீவு நாடு',
    distractors: ['ள', 'ழ'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_032',
    word: 'அலகு',
    targetLetter: 'ல',
    difficulty: 'medium',
    meaningEnglish: 'unit',
    meaningTamil: 'அளவிடும் அலகு',
    distractors: ['ள', 'ழ'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_033',
    word: 'உலோகம்',
    targetLetter: 'ல',
    difficulty: 'medium',
    meaningEnglish: 'metal',
    meaningTamil: 'கனிமப் பொருள்',
    distractors: ['ளோ', 'ழோ'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_034',
    word: 'கலந்தது',
    targetLetter: 'ல',
    difficulty: 'medium',
    meaningEnglish: 'mixed',
    meaningTamil: 'சேர்ந்தது',
    distractors: ['ள', 'ழ'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_035',
    word: 'மலர்',
    targetLetter: 'ல',
    difficulty: 'easy',
    meaningEnglish: 'flower',
    meaningTamil: 'பூ',
    distractors: ['ள', 'ழ'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_036',
    word: 'பலர்',
    targetLetter: 'ல',
    difficulty: 'easy',
    meaningEnglish: 'many people',
    meaningTamil: 'பல மனிதர்கள்',
    distractors: ['ள', 'ழ'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_037',
    word: 'சிலர்',
    targetLetter: 'ல',
    difficulty: 'easy',
    meaningEnglish: 'some people',
    meaningTamil: 'சில மனிதர்கள்',
    distractors: ['ள', 'ழ'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_038',
    word: 'இலக்கு',
    targetLetter: 'ல',
    difficulty: 'medium',
    meaningEnglish: 'goal / target',
    meaningTamil: 'அடைய வேண்டிய குறிக்கோள்',
    distractors: ['ள', 'ழ'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_039',
    word: 'விலக்கு',
    targetLetter: 'ல',
    difficulty: 'medium',
    meaningEnglish: 'exclude / exception',
    meaningTamil: 'நீக்குதல் / விதிவிலக்கு',
    distractors: ['ள', 'ழ'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_040',
    word: 'பள்ளி',
    targetLetter: 'ள',
    difficulty: 'easy',
    meaningEnglish: 'school',
    meaningTamil: 'கல்வி கற்கும் இடம்',
    distractors: ['ல்', 'ழ்'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_041',
    word: 'பள்ளம்',
    targetLetter: 'ள',
    difficulty: 'easy',
    meaningEnglish: 'pit / depression',
    meaningTamil: 'தாழ்வான குழி',
    distractors: ['ல்', 'ழ்'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_042',
    word: 'வெள்ளம்',
    targetLetter: 'ள',
    difficulty: 'easy',
    meaningEnglish: 'flood',
    meaningTamil: 'பெருகிய நீர்',
    distractors: ['ல்', 'ழ்'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_043',
    word: 'வள்ளி',
    targetLetter: 'ள',
    difficulty: 'easy',
    meaningEnglish: 'creeper / name',
    meaningTamil: 'கொடி வகை / பெயர்',
    distractors: ['ல்', 'ழ்'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_044',
    word: 'தள்ளு',
    targetLetter: 'ள',
    difficulty: 'easy',
    meaningEnglish: 'push',
    meaningTamil: 'அப்பால் நகர்த்துதல்',
    distractors: ['ல்', 'ழ்'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_045',
    word: 'கள்ளம்',
    targetLetter: 'ள',
    difficulty: 'medium',
    meaningEnglish: 'deceit',
    meaningTamil: 'வஞ்சகம்',
    distractors: ['ல்', 'ழ்'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_046',
    word: 'உள்ளம்',
    targetLetter: 'ள',
    difficulty: 'easy',
    meaningEnglish: 'heart / mind',
    meaningTamil: 'மனம்',
    distractors: ['ல்', 'ழ்'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_047',
    word: 'வெள்ளை',
    targetLetter: 'ள',
    difficulty: 'easy',
    meaningEnglish: 'white',
    meaningTamil: 'ஒரு நிறம்',
    distractors: ['ல்', 'ழ்'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_048',
    word: 'பிள்ளை',
    targetLetter: 'ள',
    difficulty: 'easy',
    meaningEnglish: 'child',
    meaningTamil: 'குழந்தை',
    distractors: ['ல்', 'ழ்'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_049',
    word: 'கிளி',
    targetLetter: 'ள',
    difficulty: 'easy',
    meaningEnglish: 'parrot',
    meaningTamil: 'ஒரு பறவை',
    distractors: ['லி', 'ழி'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_050',
    word: 'எள்ளு',
    targetLetter: 'ள',
    difficulty: 'easy',
    meaningEnglish: 'sesame',
    meaningTamil: 'எள் விதை',
    distractors: ['ல்', 'ழ்'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_051',
    word: 'துளி',
    targetLetter: 'ள',
    difficulty: 'easy',
    meaningEnglish: 'drop',
    meaningTamil: 'சிறு தண்ணீர் துளி',
    distractors: ['லி', 'ழி'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_052',
    word: 'குளம்',
    targetLetter: 'ள',
    difficulty: 'easy',
    meaningEnglish: 'pond',
    meaningTamil: 'நீர்நிலை',
    distractors: ['ல', 'ழ'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_053',
    word: 'குளிர்',
    targetLetter: 'ள',
    difficulty: 'easy',
    meaningEnglish: 'cold',
    meaningTamil: 'குறைந்த வெப்பநிலை',
    distractors: ['லி', 'ழி'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_054',
    word: 'விளக்கு',
    targetLetter: 'ள',
    difficulty: 'easy',
    meaningEnglish: 'lamp',
    meaningTamil: 'ஒளி தரும் கருவி',
    distractors: ['ல', 'ழ'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_055',
    word: 'விளையாட்டு',
    targetLetter: 'ள',
    difficulty: 'easy',
    meaningEnglish: 'game / play',
    meaningTamil: 'மகிழ்ச்சிக்கான செயல்',
    distractors: ['லை', 'ழை'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_056',
    word: 'வளையல்',
    targetLetter: 'ள',
    difficulty: 'easy',
    meaningEnglish: 'bangle',
    meaningTamil: 'கையில் அணியும் ஆபரணம்',
    distractors: ['லை', 'ழை'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_057',
    word: 'வளம்',
    targetLetter: 'ள',
    difficulty: 'medium',
    meaningEnglish: 'prosperity',
    meaningTamil: 'செழிப்பு',
    distractors: ['ல', 'ழ'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_058',
    word: 'அளவு',
    targetLetter: 'ள',
    difficulty: 'easy',
    meaningEnglish: 'measure / amount',
    meaningTamil: 'மாத்திரை / அளவீடு',
    distractors: ['ல', 'ழ'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_059',
    word: 'அள்ளு',
    targetLetter: 'ள',
    difficulty: 'medium',
    meaningEnglish: 'scoop',
    meaningTamil: 'கையால் நிறைய எடுப்பது',
    distractors: ['ல்', 'ழ்'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_060',
    word: 'தளம்',
    targetLetter: 'ள',
    difficulty: 'medium',
    meaningEnglish: 'platform / level',
    meaningTamil: 'அடித்தளம் / நிலை',
    distractors: ['ல', 'ழ'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_061',
    word: 'களம்',
    targetLetter: 'ள',
    difficulty: 'medium',
    meaningEnglish: 'field / arena',
    meaningTamil: 'இடம் / அரங்கம்',
    distractors: ['ல', 'ழ'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_062',
    word: 'விளைவு',
    targetLetter: 'ள',
    difficulty: 'medium',
    meaningEnglish: 'result / effect',
    meaningTamil: 'முடிவு / பயன்',
    distractors: ['லை', 'ழை'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_063',
    word: 'விளைச்சல்',
    targetLetter: 'ள',
    difficulty: 'medium',
    meaningEnglish: 'harvest / yield',
    meaningTamil: 'பயிரின் உற்பத்தி',
    distractors: ['லை', 'ழை'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_064',
    word: 'தெளிவு',
    targetLetter: 'ள',
    difficulty: 'medium',
    meaningEnglish: 'clarity',
    meaningTamil: 'புரியும் தன்மை',
    distractors: ['லி', 'ழி'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_065',
    word: 'ஒளி',
    targetLetter: 'ள',
    difficulty: 'easy',
    meaningEnglish: 'light',
    meaningTamil: 'வெளிச்சம்',
    distractors: ['லி', 'ழி'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_066',
    word: 'வளர்',
    targetLetter: 'ள',
    difficulty: 'easy',
    meaningEnglish: 'grow',
    meaningTamil: 'பெரிதாகுதல்',
    distractors: ['ல', 'ழ'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_067',
    word: 'வளர்ச்சி',
    targetLetter: 'ள',
    difficulty: 'medium',
    meaningEnglish: 'growth',
    meaningTamil: 'மேம்பாடு',
    distractors: ['ல', 'ழ'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_068',
    word: 'களிப்பு',
    targetLetter: 'ள',
    difficulty: 'medium',
    meaningEnglish: 'joy',
    meaningTamil: 'மகிழ்ச்சி',
    distractors: ['லி', 'ழி'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_069',
    word: 'தளிர்',
    targetLetter: 'ள',
    difficulty: 'medium',
    meaningEnglish: 'tender shoot',
    meaningTamil: 'புதிய இலை / முளை',
    distractors: ['லி', 'ழி'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_070',
    word: 'கிளை',
    targetLetter: 'ள',
    difficulty: 'easy',
    meaningEnglish: 'branch',
    meaningTamil: 'மரத்தின் பகுதி',
    distractors: ['லை', 'ழை'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_071',
    word: 'மிளகு',
    targetLetter: 'ள',
    difficulty: 'easy',
    meaningEnglish: 'pepper',
    meaningTamil: 'ஒரு மசாலா',
    distractors: ['ல', 'ழ'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_072',
    word: 'மிளகாய்',
    targetLetter: 'ள',
    difficulty: 'easy',
    meaningEnglish: 'chili',
    meaningTamil: 'காரமான காய்',
    distractors: ['ல', 'ழ'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_073',
    word: 'குளியல்',
    targetLetter: 'ள',
    difficulty: 'easy',
    meaningEnglish: 'bath',
    meaningTamil: 'உடலை நீரால் கழுவுதல்',
    distractors: ['லி', 'ழி'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_074',
    word: 'விளக்கம்',
    targetLetter: 'ள',
    difficulty: 'medium',
    meaningEnglish: 'explanation',
    meaningTamil: 'தெளிவுபடுத்தும் உரை',
    distractors: ['ல', 'ழ'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_075',
    word: 'அளித்தல்',
    targetLetter: 'ள',
    difficulty: 'medium',
    meaningEnglish: 'giving',
    meaningTamil: 'கொடுத்தல்',
    distractors: ['லி', 'ழி'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_076',
    word: 'துளசி',
    targetLetter: 'ள',
    difficulty: 'easy',
    meaningEnglish: 'holy basil',
    meaningTamil: 'மூலிகைச் செடி',
    distractors: ['ல', 'ழ'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_077',
    word: 'வளிமண்டலம்',
    targetLetter: 'ள',
    difficulty: 'hard',
    meaningEnglish: 'atmosphere',
    meaningTamil: 'பூமியைச் சூழ்ந்த காற்றுப்படலம்',
    distractors: ['லி', 'ழி'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_078',
    word: 'பள்ளத்தாக்கு',
    targetLetter: 'ள',
    difficulty: 'hard',
    meaningEnglish: 'valley',
    meaningTamil: 'மலைகளுக்கிடையிலான தாழ்வுநிலம்',
    distractors: ['ல்', 'ழ்'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_079',
    word: 'வெள்ளிக்கிழமை',
    targetLetter: 'ள',
    difficulty: 'medium',
    meaningEnglish: 'Friday',
    meaningTamil: 'வாரத்தின் ஒரு நாள்',
    distractors: ['ல்', 'ழ்'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_080',
    word: 'பழம்',
    targetLetter: 'ழ',
    difficulty: 'easy',
    meaningEnglish: 'fruit',
    meaningTamil: 'கனி',
    distractors: ['ல', 'ள'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_081',
    word: 'மழை',
    targetLetter: 'ழ',
    difficulty: 'easy',
    meaningEnglish: 'rain',
    meaningTamil: 'வானிலிருந்து விழும் நீர்',
    distractors: ['லை', 'ளை'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_082',
    word: 'தமிழ்',
    targetLetter: 'ழ',
    difficulty: 'easy',
    meaningEnglish: 'Tamil',
    meaningTamil: 'தமிழ் மொழி',
    distractors: ['ல்', 'ள்'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_083',
    word: 'அழகு',
    targetLetter: 'ழ',
    difficulty: 'easy',
    meaningEnglish: 'beauty',
    meaningTamil: 'இனிமையான தோற்றம்',
    distractors: ['ல', 'ள'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_084',
    word: 'வாழை',
    targetLetter: 'ழ',
    difficulty: 'easy',
    meaningEnglish: 'banana plant',
    meaningTamil: 'ஒரு பழமரம்',
    distractors: ['லை', 'ளை'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_085',
    word: 'வாழ்த்து',
    targetLetter: 'ழ',
    difficulty: 'easy',
    meaningEnglish: 'greeting / wish',
    meaningTamil: 'நல்விருப்புச் சொல்',
    distractors: ['ல்', 'ள்'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_086',
    word: 'வாழ்வு',
    targetLetter: 'ழ',
    difficulty: 'easy',
    meaningEnglish: 'life',
    meaningTamil: 'உயிருடன் வாழும் நிலை',
    distractors: ['ல்', 'ள்'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_087',
    word: 'வாழ்க்கை',
    targetLetter: 'ழ',
    difficulty: 'easy',
    meaningEnglish: 'life',
    meaningTamil: 'உயிர் வாழும் பயணம்',
    distractors: ['ல்', 'ள்'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_088',
    word: 'கழுகு',
    targetLetter: 'ழ',
    difficulty: 'easy',
    meaningEnglish: 'eagle',
    meaningTamil: 'ஒரு வேட்டைப் பறவை',
    distractors: ['லு', 'ளு'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_089',
    word: 'கழுத்து',
    targetLetter: 'ழ',
    difficulty: 'easy',
    meaningEnglish: 'neck',
    meaningTamil: 'தலைக்கும் உடலுக்கும் இடைப்பட்ட பகுதி',
    distractors: ['லு', 'ளு'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_090',
    word: 'கிழங்கு',
    targetLetter: 'ழ',
    difficulty: 'easy',
    meaningEnglish: 'tuber',
    meaningTamil: 'மண்ணுக்குள் வளரும் உணவு',
    distractors: ['ல', 'ள'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_091',
    word: 'கிழக்கு',
    targetLetter: 'ழ',
    difficulty: 'easy',
    meaningEnglish: 'east',
    meaningTamil: 'சூரியன் உதிக்கும் திசை',
    distractors: ['ல', 'ள'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_092',
    word: 'குழந்தை',
    targetLetter: 'ழ',
    difficulty: 'easy',
    meaningEnglish: 'child',
    meaningTamil: 'சிறு வயது மனிதர்',
    distractors: ['ல', 'ள'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_093',
    word: 'குழல்',
    targetLetter: 'ழ',
    difficulty: 'medium',
    meaningEnglish: 'tube / flute',
    meaningTamil: 'குழாய் / இசைக்கருவி',
    distractors: ['ல', 'ள'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_094',
    word: 'குழம்பு',
    targetLetter: 'ழ',
    difficulty: 'easy',
    meaningEnglish: 'gravy / curry',
    meaningTamil: 'திரவ உணவு வகை',
    distractors: ['ல', 'ள'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_095',
    word: 'குழி',
    targetLetter: 'ழ',
    difficulty: 'easy',
    meaningEnglish: 'hole',
    meaningTamil: 'தரையில் உள்ள பள்ளம்',
    distractors: ['லி', 'ளி'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_096',
    word: 'எழுது',
    targetLetter: 'ழ',
    difficulty: 'easy',
    meaningEnglish: 'write',
    meaningTamil: 'எழுத்துகளைப் பதிவு செய்',
    distractors: ['லு', 'ளு'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_097',
    word: 'எழுத்து',
    targetLetter: 'ழ',
    difficulty: 'easy',
    meaningEnglish: 'letter / character',
    meaningTamil: 'மொழியின் குறியீடு',
    distractors: ['லு', 'ளு'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_098',
    word: 'எழில்',
    targetLetter: 'ழ',
    difficulty: 'medium',
    meaningEnglish: 'grace / beauty',
    meaningTamil: 'அழகு',
    distractors: ['லி', 'ளி'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_099',
    word: 'எழுந்திரு',
    targetLetter: 'ழ',
    difficulty: 'easy',
    meaningEnglish: 'get up',
    meaningTamil: 'படுக்கையிலிருந்து எழு',
    distractors: ['லு', 'ளு'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_100',
    word: 'விழா',
    targetLetter: 'ழ',
    difficulty: 'easy',
    meaningEnglish: 'festival',
    meaningTamil: 'கொண்டாட்ட நிகழ்வு',
    distractors: ['லா', 'ளா'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_101',
    word: 'விழி',
    targetLetter: 'ழ',
    difficulty: 'medium',
    meaningEnglish: 'eye',
    meaningTamil: 'கண்',
    distractors: ['லி', 'ளி'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_102',
    word: 'விழுதல்',
    targetLetter: 'ழ',
    difficulty: 'easy',
    meaningEnglish: 'falling',
    meaningTamil: 'கீழே சரிதல்',
    distractors: ['லு', 'ளு'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_103',
    word: 'வழி',
    targetLetter: 'ழ',
    difficulty: 'easy',
    meaningEnglish: 'way / path',
    meaningTamil: 'பாதை / முறை',
    distractors: ['லி', 'ளி'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_104',
    word: 'வழக்கம்',
    targetLetter: 'ழ',
    difficulty: 'medium',
    meaningEnglish: 'custom / habit',
    meaningTamil: 'தொடர்ந்து செய்யும் பழக்கம்',
    distractors: ['ல', 'ள'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_105',
    word: 'வழங்குதல்',
    targetLetter: 'ழ',
    difficulty: 'medium',
    meaningEnglish: 'providing',
    meaningTamil: 'கொடுத்தல்',
    distractors: ['ல', 'ள'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_106',
    word: 'அழை',
    targetLetter: 'ழ',
    difficulty: 'easy',
    meaningEnglish: 'call / invite',
    meaningTamil: 'வருமாறு கூப்பிடு',
    distractors: ['லை', 'ளை'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_107',
    word: 'அழுகை',
    targetLetter: 'ழ',
    difficulty: 'easy',
    meaningEnglish: 'crying',
    meaningTamil: 'அழும் செயல்',
    distractors: ['லு', 'ளு'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_108',
    word: 'அழுத்தம்',
    targetLetter: 'ழ',
    difficulty: 'medium',
    meaningEnglish: 'pressure',
    meaningTamil: 'தள்ளும் விசை / மனச்சுமை',
    distractors: ['லு', 'ளு'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_109',
    word: 'பழக்கம்',
    targetLetter: 'ழ',
    difficulty: 'easy',
    meaningEnglish: 'habit',
    meaningTamil: 'தொடர்ந்து செய்யும் நடை',
    distractors: ['ல', 'ள'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_110',
    word: 'பழைய',
    targetLetter: 'ழ',
    difficulty: 'easy',
    meaningEnglish: 'old',
    meaningTamil: 'புதியதல்லாத',
    distractors: ['லை', 'ளை'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_111',
    word: 'பழுப்பு',
    targetLetter: 'ழ',
    difficulty: 'easy',
    meaningEnglish: 'brown',
    meaningTamil: 'ஒரு நிறம்',
    distractors: ['லு', 'ளு'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_112',
    word: 'தொழில்',
    targetLetter: 'ழ',
    difficulty: 'medium',
    meaningEnglish: 'occupation',
    meaningTamil: 'வேலை / வியாபாரம்',
    distractors: ['லி', 'ளி'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_113',
    word: 'தொழிலாளர்',
    targetLetter: 'ழ',
    difficulty: 'medium',
    meaningEnglish: 'worker',
    meaningTamil: 'வேலை செய்பவர்',
    distractors: ['லி', 'ளி'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_114',
    word: 'செழிப்பு',
    targetLetter: 'ழ',
    difficulty: 'medium',
    meaningEnglish: 'prosperity',
    meaningTamil: 'வளம் நிறைந்த நிலை',
    distractors: ['லி', 'ளி'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_115',
    word: 'ஆழம்',
    targetLetter: 'ழ',
    difficulty: 'medium',
    meaningEnglish: 'depth',
    meaningTamil: 'மேலிருந்து கீழுள்ள தூரம்',
    distractors: ['ல', 'ள'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_116',
    word: 'ஆழமான',
    targetLetter: 'ழ',
    difficulty: 'medium',
    meaningEnglish: 'deep',
    meaningTamil: 'மிகுந்த ஆழமுள்ள',
    distractors: ['ல', 'ள'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_117',
    word: 'முழு',
    targetLetter: 'ழ',
    difficulty: 'easy',
    meaningEnglish: 'whole / full',
    meaningTamil: 'எல்லாம் சேர்ந்த',
    distractors: ['லு', 'ளு'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_118',
    word: 'முழக்கம்',
    targetLetter: 'ழ',
    difficulty: 'medium',
    meaningEnglish: 'roar / resonance',
    meaningTamil: 'உரத்த ஒலி',
    distractors: ['ல', 'ள'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_119',
    word: 'முழங்கை',
    targetLetter: 'ழ',
    difficulty: 'easy',
    meaningEnglish: 'elbow',
    meaningTamil: 'கையின் மடிப்பு மூட்டு',
    distractors: ['ல', 'ள'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_120',
    word: 'நான்',
    targetLetter: 'ன',
    difficulty: 'easy',
    meaningEnglish: 'I',
    meaningTamil: 'தன்னைச் சுட்டும் சொல்',
    distractors: ['ண்', 'ந்', 'ல்'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_121',
    word: 'தான்',
    targetLetter: 'ன',
    difficulty: 'easy',
    meaningEnglish: 'self / indeed',
    meaningTamil: 'தன்னையே குறிக்கும் சொல்',
    distractors: ['ண்', 'ந்', 'ல்'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_122',
    word: 'வான்',
    targetLetter: 'ன',
    difficulty: 'easy',
    meaningEnglish: 'sky',
    meaningTamil: 'வானம்',
    distractors: ['ண்', 'ந்', 'ல்'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_123',
    word: 'மான்',
    targetLetter: 'ன',
    difficulty: 'easy',
    meaningEnglish: 'deer',
    meaningTamil: 'ஒரு காட்டு விலங்கு',
    distractors: ['ண்', 'ந்', 'ல்'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_124',
    word: 'மீன்',
    targetLetter: 'ன',
    difficulty: 'easy',
    meaningEnglish: 'fish',
    meaningTamil: 'நீரில் வாழும் உயிரி',
    distractors: ['ண்', 'ந்', 'ல்'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_125',
    word: 'தேன்',
    targetLetter: 'ன',
    difficulty: 'easy',
    meaningEnglish: 'honey',
    meaningTamil: 'தேனீ தரும் இனிப்புப் பொருள்',
    distractors: ['ண்', 'ந்', 'ல்'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_126',
    word: 'ஏன்',
    targetLetter: 'ன',
    difficulty: 'easy',
    meaningEnglish: 'why',
    meaningTamil: 'காரணம் கேட்கும் சொல்',
    distractors: ['ண்', 'ந்', 'ல்'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_127',
    word: 'அவன்',
    targetLetter: 'ன',
    difficulty: 'easy',
    meaningEnglish: 'he',
    meaningTamil: 'ஆண் ஒருவரைக் குறிக்கும் சொல்',
    distractors: ['ண்', 'ந்', 'ல்'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_128',
    word: 'இவன்',
    targetLetter: 'ன',
    difficulty: 'easy',
    meaningEnglish: 'this man / he',
    meaningTamil: 'அருகிலுள்ள ஆணைக் குறிக்கும் சொல்',
    distractors: ['ண்', 'ந்', 'ல்'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_129',
    word: 'எவன்',
    targetLetter: 'ன',
    difficulty: 'medium',
    meaningEnglish: 'who (male)',
    meaningTamil: 'யார் என்ற வினா வடிவம்',
    distractors: ['ண்', 'ந்', 'ல்'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_130',
    word: 'அவனது',
    targetLetter: 'ன',
    difficulty: 'easy',
    meaningEnglish: 'his',
    meaningTamil: 'அவனுக்குச் சொந்தமான',
    distractors: ['ண', 'ந', 'ல'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_131',
    word: 'எனது',
    targetLetter: 'ன',
    difficulty: 'easy',
    meaningEnglish: 'mine / my',
    meaningTamil: 'எனக்குச் சொந்தமான',
    distractors: ['ண', 'ந', 'ல'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_132',
    word: 'உனது',
    targetLetter: 'ன',
    difficulty: 'easy',
    meaningEnglish: 'yours / your',
    meaningTamil: 'உனக்குச் சொந்தமான',
    distractors: ['ண', 'ந', 'ல'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_133',
    word: 'தனது',
    targetLetter: 'ன',
    difficulty: 'medium',
    meaningEnglish: 'one\'s own',
    meaningTamil: 'தனக்குச் சொந்தமான',
    distractors: ['ண', 'ந', 'ல'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_134',
    word: 'மனம்',
    targetLetter: 'ன',
    difficulty: 'easy',
    meaningEnglish: 'mind',
    meaningTamil: 'உள்ளுணர்வு / சிந்தனை',
    distractors: ['ண', 'ந', 'ல'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_135',
    word: 'தினம்',
    targetLetter: 'ன',
    difficulty: 'easy',
    meaningEnglish: 'day / daily',
    meaningTamil: 'ஒவ்வொரு நாள்',
    distractors: ['ண', 'ந', 'ல'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_136',
    word: 'இனம்',
    targetLetter: 'ன',
    difficulty: 'easy',
    meaningEnglish: 'kind / group',
    meaningTamil: 'வகை / மக்கள் பிரிவு',
    distractors: ['ண', 'ந', 'ல'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_137',
    word: 'சினம்',
    targetLetter: 'ன',
    difficulty: 'medium',
    meaningEnglish: 'anger',
    meaningTamil: 'கோபம்',
    distractors: ['ண', 'ந', 'ல'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_138',
    word: 'பனம்',
    targetLetter: 'ன',
    difficulty: 'medium',
    meaningEnglish: 'palmyra-related',
    meaningTamil: 'பனை தொடர்பான சொல்',
    distractors: ['ண', 'ந', 'ல'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_139',
    word: 'கனவு',
    targetLetter: 'ன',
    difficulty: 'easy',
    meaningEnglish: 'dream',
    meaningTamil: 'தூக்கத்தில் தோன்றும் காட்சி',
    distractors: ['ண', 'ந', 'ல'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_140',
    word: 'நினைவு',
    targetLetter: 'ன',
    difficulty: 'easy',
    meaningEnglish: 'memory',
    meaningTamil: 'ஞாபகம்',
    distractors: ['ணை', 'நை', 'லை'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_141',
    word: 'புனல்',
    targetLetter: 'ன',
    difficulty: 'medium',
    meaningEnglish: 'water',
    meaningTamil: 'நீர்',
    distractors: ['ண', 'ந', 'ல'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_142',
    word: 'முனை',
    targetLetter: 'ன',
    difficulty: 'medium',
    meaningEnglish: 'tip / edge',
    meaningTamil: 'நுனி / முன்பகுதி',
    distractors: ['ணை', 'நை', 'லை'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_143',
    word: 'தினை',
    targetLetter: 'ன',
    difficulty: 'medium',
    meaningEnglish: 'foxtail millet',
    meaningTamil: 'ஒரு சிறுதானியம்',
    distractors: ['ணை', 'நை', 'லை'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_144',
    word: 'வினை',
    targetLetter: 'ன',
    difficulty: 'medium',
    meaningEnglish: 'action / deed',
    meaningTamil: 'செயல்',
    distractors: ['ணை', 'நை', 'லை'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_145',
    word: 'மனை',
    targetLetter: 'ன',
    difficulty: 'medium',
    meaningEnglish: 'house site / home',
    meaningTamil: 'வீட்டு நிலம் / இல்லம்',
    distractors: ['ணை', 'நை', 'லை'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_146',
    word: 'மனைவி',
    targetLetter: 'ன',
    difficulty: 'easy',
    meaningEnglish: 'wife',
    meaningTamil: 'திருமணமான பெண் துணை',
    distractors: ['ணை', 'நை', 'லை'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_147',
    word: 'மனிதன்',
    targetLetter: 'ன',
    difficulty: 'easy',
    meaningEnglish: 'man / human',
    meaningTamil: 'மனித ஆண்',
    distractors: ['ணி', 'நி', 'லி'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_148',
    word: 'மாணவன்',
    targetLetter: 'ன',
    difficulty: 'easy',
    meaningEnglish: 'male student',
    meaningTamil: 'ஆண் மாணவர்',
    distractors: ['ண்', 'ந்', 'ல்'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_149',
    word: 'தலைவன்',
    targetLetter: 'ன',
    difficulty: 'easy',
    meaningEnglish: 'leader',
    meaningTamil: 'முன்னிலை வகிப்பவர்',
    distractors: ['ண்', 'ந்', 'ல்'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_150',
    word: 'இளைஞன்',
    targetLetter: 'ன',
    difficulty: 'medium',
    meaningEnglish: 'young man',
    meaningTamil: 'இளம் ஆண்',
    distractors: ['ண்', 'ந்', 'ல்'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_151',
    word: 'நண்பன்',
    targetLetter: 'ன',
    difficulty: 'easy',
    meaningEnglish: 'male friend',
    meaningTamil: 'ஆண் நண்பர்',
    distractors: ['ண்', 'ந்', 'ல்'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_152',
    word: 'அன்பன்',
    targetLetter: 'ன',
    difficulty: 'medium',
    meaningEnglish: 'loving person',
    meaningTamil: 'அன்புடையவன்',
    distractors: ['ண்', 'ந்', 'ல்'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_153',
    word: 'செல்வன்',
    targetLetter: 'ன',
    difficulty: 'medium',
    meaningEnglish: 'young man',
    meaningTamil: 'இளைஞன் / ஆண் பெயர்ச்சொல்',
    distractors: ['ண்', 'ந்', 'ல்'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_154',
    word: 'அரசன்',
    targetLetter: 'ன',
    difficulty: 'easy',
    meaningEnglish: 'king',
    meaningTamil: 'நாட்டை ஆளும் ஆண்',
    distractors: ['ண்', 'ந்', 'ல்'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_155',
    word: 'வீரன்',
    targetLetter: 'ன',
    difficulty: 'easy',
    meaningEnglish: 'hero / brave man',
    meaningTamil: 'துணிச்சலான ஆண்',
    distractors: ['ண்', 'ந்', 'ல்'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_156',
    word: 'கலைஞன்',
    targetLetter: 'ன',
    difficulty: 'medium',
    meaningEnglish: 'artist',
    meaningTamil: 'கலை செய்பவர்',
    distractors: ['ண்', 'ந்', 'ல்'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_157',
    word: 'அறிஞன்',
    targetLetter: 'ன',
    difficulty: 'medium',
    meaningEnglish: 'scholar',
    meaningTamil: 'அறிவு மிக்கவர்',
    distractors: ['ண்', 'ந்', 'ல்'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_158',
    word: 'உழவன்',
    targetLetter: 'ன',
    difficulty: 'easy',
    meaningEnglish: 'farmer',
    meaningTamil: 'விவசாயி',
    distractors: ['ண்', 'ந்', 'ல்'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_159',
    word: 'கண்',
    targetLetter: 'ண',
    difficulty: 'easy',
    meaningEnglish: 'eye',
    meaningTamil: 'பார்க்கும் உறுப்பு',
    distractors: ['ன்', 'ந்', 'ல்'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_160',
    word: 'மண்',
    targetLetter: 'ண',
    difficulty: 'easy',
    meaningEnglish: 'soil / earth',
    meaningTamil: 'நிலத்தின் மண்',
    distractors: ['ன்', 'ந்', 'ல்'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_161',
    word: 'பெண்',
    targetLetter: 'ண',
    difficulty: 'easy',
    meaningEnglish: 'woman / girl',
    meaningTamil: 'பெண் மனிதர்',
    distractors: ['ன்', 'ந்', 'ல்'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_162',
    word: 'எண்',
    targetLetter: 'ண',
    difficulty: 'easy',
    meaningEnglish: 'number',
    meaningTamil: 'எண்ணிக்கை குறியீடு',
    distractors: ['ன்', 'ந்', 'ல்'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_163',
    word: 'பண்',
    targetLetter: 'ண',
    difficulty: 'hard',
    meaningEnglish: 'musical mode',
    meaningTamil: 'இசை முறை',
    distractors: ['ன்', 'ந்', 'ல்'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_164',
    word: 'மணி',
    targetLetter: 'ண',
    difficulty: 'easy',
    meaningEnglish: 'hour / bell',
    meaningTamil: 'நேர அளவு / மணி',
    distractors: ['னி', 'நி', 'லி'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_165',
    word: 'அணி',
    targetLetter: 'ண',
    difficulty: 'medium',
    meaningEnglish: 'ornament / team',
    meaningTamil: 'அலங்காரம் / குழு',
    distractors: ['னி', 'நி', 'லி'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_166',
    word: 'பணி',
    targetLetter: 'ண',
    difficulty: 'easy',
    meaningEnglish: 'task / service',
    meaningTamil: 'வேலை / சேவை',
    distractors: ['னி', 'நி', 'லி'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_167',
    word: 'துணி',
    targetLetter: 'ண',
    difficulty: 'easy',
    meaningEnglish: 'cloth',
    meaningTamil: 'ஆடைத் துணி',
    distractors: ['னி', 'நி', 'லி'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_168',
    word: 'குணம்',
    targetLetter: 'ண',
    difficulty: 'easy',
    meaningEnglish: 'quality / character',
    meaningTamil: 'தன்மை',
    distractors: ['ன', 'ந', 'ல'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_169',
    word: 'மணம்',
    targetLetter: 'ண',
    difficulty: 'easy',
    meaningEnglish: 'fragrance / marriage',
    meaningTamil: 'வாசனை / திருமணம்',
    distractors: ['ன', 'ந', 'ல'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_170',
    word: 'கணம்',
    targetLetter: 'ண',
    difficulty: 'medium',
    meaningEnglish: 'moment',
    meaningTamil: 'மிகச் சிறிய நேரம்',
    distractors: ['ன', 'ந', 'ல'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_171',
    word: 'திணை',
    targetLetter: 'ண',
    difficulty: 'hard',
    meaningEnglish: 'landscape genre / millet',
    meaningTamil: 'தமிழ் இலக்கிய வகை / தானியம்',
    distractors: ['னை', 'நை', 'லை'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_172',
    word: 'துணை',
    targetLetter: 'ண',
    difficulty: 'easy',
    meaningEnglish: 'support / companion',
    meaningTamil: 'உதவி / சேர்ந்து இருப்பவர்',
    distractors: ['னை', 'நை', 'லை'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_173',
    word: 'இணை',
    targetLetter: 'ண',
    difficulty: 'medium',
    meaningEnglish: 'pair / connect',
    meaningTamil: 'ஜோடி / இணைத்தல்',
    distractors: ['னை', 'நை', 'லை'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_174',
    word: 'அணில்',
    targetLetter: 'ண',
    difficulty: 'easy',
    meaningEnglish: 'squirrel',
    meaningTamil: 'ஒரு சிறு விலங்கு',
    distractors: ['னி', 'நி', 'லி'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_175',
    word: 'கிணறு',
    targetLetter: 'ண',
    difficulty: 'easy',
    meaningEnglish: 'well',
    meaningTamil: 'நீர் எடுக்கும் ஆழ்குழி',
    distractors: ['ன', 'ந', 'ல'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_176',
    word: 'புண்',
    targetLetter: 'ண',
    difficulty: 'easy',
    meaningEnglish: 'sore / wound',
    meaningTamil: 'உடலில் ஏற்பட்ட காயம்',
    distractors: ['ன்', 'ந்', 'ல்'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_177',
    word: 'விண்',
    targetLetter: 'ண',
    difficulty: 'medium',
    meaningEnglish: 'sky',
    meaningTamil: 'வானம்',
    distractors: ['ன்', 'ந்', 'ல்'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_178',
    word: 'வண்ணம்',
    targetLetter: 'ண',
    difficulty: 'easy',
    meaningEnglish: 'color',
    meaningTamil: 'நிறம்',
    distractors: ['ன்', 'ந்', 'ல்'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_179',
    word: 'எண்ணம்',
    targetLetter: 'ண',
    difficulty: 'easy',
    meaningEnglish: 'thought',
    meaningTamil: 'சிந்தனை',
    distractors: ['ன்', 'ந்', 'ல்'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_180',
    word: 'கண்ணாடி',
    targetLetter: 'ண',
    difficulty: 'easy',
    meaningEnglish: 'mirror / glass',
    meaningTamil: 'பார்க்கும் கண்ணாடி',
    distractors: ['ன்', 'ந்', 'ல்'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_181',
    word: 'கண்ணீர்',
    targetLetter: 'ண',
    difficulty: 'easy',
    meaningEnglish: 'tears',
    meaningTamil: 'கண்ணிலிருந்து வரும் நீர்',
    distractors: ['ன்', 'ந்', 'ல்'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_182',
    word: 'தண்ணீர்',
    targetLetter: 'ண',
    difficulty: 'easy',
    meaningEnglish: 'water',
    meaningTamil: 'குடிக்கும் நீர்',
    distractors: ['ன்', 'ந்', 'ல்'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_183',
    word: 'வெண்ணெய்',
    targetLetter: 'ண',
    difficulty: 'easy',
    meaningEnglish: 'butter',
    meaningTamil: 'பாலிலிருந்து பெறும் உணவு',
    distractors: ['ன்', 'ந்', 'ல்'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_184',
    word: 'எண்ணெய்',
    targetLetter: 'ண',
    difficulty: 'easy',
    meaningEnglish: 'oil',
    meaningTamil: 'கொழுப்பு திரவம்',
    distractors: ['ன்', 'ந்', 'ல்'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_185',
    word: 'உணவு',
    targetLetter: 'ண',
    difficulty: 'easy',
    meaningEnglish: 'food',
    meaningTamil: 'சாப்பாடு',
    distractors: ['ன', 'ந', 'ல'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_186',
    word: 'உண்மை',
    targetLetter: 'ண',
    difficulty: 'easy',
    meaningEnglish: 'truth',
    meaningTamil: 'பொய்யல்லாதது',
    distractors: ['ன்', 'ந்', 'ல்'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_187',
    word: 'உணர்வு',
    targetLetter: 'ண',
    difficulty: 'medium',
    meaningEnglish: 'feeling / awareness',
    meaningTamil: 'உணரும் தன்மை',
    distractors: ['ன', 'ந', 'ல'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_188',
    word: 'உணர்ச்சி',
    targetLetter: 'ண',
    difficulty: 'medium',
    meaningEnglish: 'emotion',
    meaningTamil: 'மன உணர்வு',
    distractors: ['ன', 'ந', 'ல'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_189',
    word: 'கணக்கு',
    targetLetter: 'ண',
    difficulty: 'easy',
    meaningEnglish: 'calculation / math',
    meaningTamil: 'எண்ணும் பாடம் / கணிதம்',
    distractors: ['ன', 'ந', 'ல'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_190',
    word: 'கணினி',
    targetLetter: 'ண',
    difficulty: 'easy',
    meaningEnglish: 'computer',
    meaningTamil: 'மின்னணுக் கணிப்பொறி',
    distractors: ['னி', 'நி', 'லி'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_191',
    word: 'அண்ணன்',
    targetLetter: 'ண',
    difficulty: 'easy',
    meaningEnglish: 'elder brother',
    meaningTamil: 'மூத்த ஆண் உடன்பிறப்பு',
    distractors: ['ன்', 'ந்', 'ல்'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_192',
    word: 'தண்ணீரில்',
    targetLetter: 'ண',
    difficulty: 'easy',
    meaningEnglish: 'in water',
    meaningTamil: 'தண்ணீருக்குள்',
    distractors: ['ன்', 'ந்', 'ல்'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_193',
    word: 'பண்ணை',
    targetLetter: 'ண',
    difficulty: 'easy',
    meaningEnglish: 'farm',
    meaningTamil: 'விவசாய நிலம்',
    distractors: ['ன்', 'ந்', 'ல்'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_194',
    word: 'மண்ணில்',
    targetLetter: 'ண',
    difficulty: 'easy',
    meaningEnglish: 'in the soil',
    meaningTamil: 'மண்ணுக்குள் / மண்ணின் மேல்',
    distractors: ['ன்', 'ந்', 'ல்'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_195',
    word: 'விண்மீன்',
    targetLetter: 'ண',
    difficulty: 'medium',
    meaningEnglish: 'star',
    meaningTamil: 'வானில் தெரியும் நட்சத்திரம்',
    distractors: ['ன்', 'ந்', 'ல்'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_196',
    word: 'கண்ணிமை',
    targetLetter: 'ண',
    difficulty: 'medium',
    meaningEnglish: 'eyelid',
    meaningTamil: 'கண்ணை மூடும் தோல்',
    distractors: ['ன்', 'ந்', 'ல்'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_197',
    word: 'திண்ணை',
    targetLetter: 'ண',
    difficulty: 'medium',
    meaningEnglish: 'veranda platform',
    meaningTamil: 'வீட்டின் முன் உயர்ந்த மேடை',
    distractors: ['ன்', 'ந்', 'ல்'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_198',
    word: 'அணை',
    targetLetter: 'ண',
    difficulty: 'easy',
    meaningEnglish: 'dam',
    meaningTamil: 'நீரைத் தடுக்கும் கட்டிடம்',
    distractors: ['னை', 'நை', 'லை'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_199',
    word: 'நாய்',
    targetLetter: 'ந',
    difficulty: 'easy',
    meaningEnglish: 'dog',
    meaningTamil: 'ஒரு வீட்டுவிலங்கு',
    distractors: ['னா', 'ணா', 'லா'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_200',
    word: 'நரி',
    targetLetter: 'ந',
    difficulty: 'easy',
    meaningEnglish: 'fox',
    meaningTamil: 'ஒரு காட்டு விலங்கு',
    distractors: ['ன', 'ண', 'ல'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_201',
    word: 'நண்டு',
    targetLetter: 'ந',
    difficulty: 'easy',
    meaningEnglish: 'crab',
    meaningTamil: 'ஒரு நீர்வாழ் உயிரி',
    distractors: ['ன', 'ண', 'ல'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_202',
    word: 'நத்தை',
    targetLetter: 'ந',
    difficulty: 'easy',
    meaningEnglish: 'snail',
    meaningTamil: 'மெதுவாக நகரும் உயிரி',
    distractors: ['ன', 'ண', 'ல'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_203',
    word: 'நிலம்',
    targetLetter: 'ந',
    difficulty: 'easy',
    meaningEnglish: 'land',
    meaningTamil: 'தரை / பூமி',
    distractors: ['னி', 'ணி', 'லி'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_204',
    word: 'நிலவு',
    targetLetter: 'ந',
    difficulty: 'easy',
    meaningEnglish: 'moon',
    meaningTamil: 'சந்திரன்',
    distractors: ['னி', 'ணி', 'லி'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_205',
    word: 'நீர்',
    targetLetter: 'ந',
    difficulty: 'easy',
    meaningEnglish: 'water',
    meaningTamil: 'தண்ணீர்',
    distractors: ['னீ', 'ணீ', 'லீ'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_206',
    word: 'நீலம்',
    targetLetter: 'ந',
    difficulty: 'easy',
    meaningEnglish: 'blue',
    meaningTamil: 'ஒரு நிறம்',
    distractors: ['னீ', 'ணீ', 'லீ'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_207',
    word: 'நூல்',
    targetLetter: 'ந',
    difficulty: 'easy',
    meaningEnglish: 'book / thread',
    meaningTamil: 'புத்தகம் / இழை',
    distractors: ['னூ', 'ணூ', 'லூ'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_208',
    word: 'நெல்',
    targetLetter: 'ந',
    difficulty: 'easy',
    meaningEnglish: 'paddy',
    meaningTamil: 'அரிசி தரும் பயிர்',
    distractors: ['னெ', 'ணெ', 'லெ'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_209',
    word: 'நெருப்பு',
    targetLetter: 'ந',
    difficulty: 'easy',
    meaningEnglish: 'fire',
    meaningTamil: 'தீ',
    distractors: ['னெ', 'ணெ', 'லெ'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_210',
    word: 'நேரம்',
    targetLetter: 'ந',
    difficulty: 'easy',
    meaningEnglish: 'time',
    meaningTamil: 'கால அளவு',
    distractors: ['னே', 'ணே', 'லே'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_211',
    word: 'நேற்று',
    targetLetter: 'ந',
    difficulty: 'easy',
    meaningEnglish: 'yesterday',
    meaningTamil: 'முந்தைய நாள்',
    distractors: ['னே', 'ணே', 'லே'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_212',
    word: 'நன்றி',
    targetLetter: 'ந',
    difficulty: 'easy',
    meaningEnglish: 'thanks',
    meaningTamil: 'நன்றியுணர்வுச் சொல்',
    distractors: ['ன', 'ண', 'ல'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_213',
    word: 'நண்பர்',
    targetLetter: 'ந',
    difficulty: 'easy',
    meaningEnglish: 'friend',
    meaningTamil: 'நட்புடையவர்',
    distractors: ['ன', 'ண', 'ல'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_214',
    word: 'நடனம்',
    targetLetter: 'ந',
    difficulty: 'easy',
    meaningEnglish: 'dance',
    meaningTamil: 'ஆடல் கலை',
    distractors: ['ன', 'ண', 'ல'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_215',
    word: 'நடப்பு',
    targetLetter: 'ந',
    difficulty: 'medium',
    meaningEnglish: 'current / ongoing',
    meaningTamil: 'இப்போது நடைபெறுவது',
    distractors: ['ன', 'ண', 'ல'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_216',
    word: 'நடை',
    targetLetter: 'ந',
    difficulty: 'easy',
    meaningEnglish: 'walk / style',
    meaningTamil: 'நடக்கும் முறை',
    distractors: ['ன', 'ண', 'ல'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_217',
    word: 'நகரம்',
    targetLetter: 'ந',
    difficulty: 'easy',
    meaningEnglish: 'city',
    meaningTamil: 'பெரிய குடியிருப்பு பகுதி',
    distractors: ['ன', 'ண', 'ல'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_218',
    word: 'நாடு',
    targetLetter: 'ந',
    difficulty: 'easy',
    meaningEnglish: 'country',
    meaningTamil: 'தேசம்',
    distractors: ['னா', 'ணா', 'லா'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_219',
    word: 'நாணயம்',
    targetLetter: 'ந',
    difficulty: 'medium',
    meaningEnglish: 'coin / integrity',
    meaningTamil: 'பணம் / நேர்மை',
    distractors: ['னா', 'ணா', 'லா'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_220',
    word: 'நாவல்',
    targetLetter: 'ந',
    difficulty: 'medium',
    meaningEnglish: 'novel / jamun',
    meaningTamil: 'நீண்ட கதை / பழம்',
    distractors: ['னா', 'ணா', 'லா'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_221',
    word: 'நாக்கு',
    targetLetter: 'ந',
    difficulty: 'easy',
    meaningEnglish: 'tongue',
    meaningTamil: 'வாயின் உறுப்பு',
    distractors: ['னா', 'ணா', 'லா'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_222',
    word: 'நாற்காலி',
    targetLetter: 'ந',
    difficulty: 'easy',
    meaningEnglish: 'chair',
    meaningTamil: 'உட்காரும் இருக்கை',
    distractors: ['னா', 'ணா', 'லா'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_223',
    word: 'நான்கு',
    targetLetter: 'ந',
    difficulty: 'easy',
    meaningEnglish: 'four',
    meaningTamil: 'எண் 4',
    distractors: ['னா', 'ணா', 'லா'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_224',
    word: 'நூறு',
    targetLetter: 'ந',
    difficulty: 'easy',
    meaningEnglish: 'hundred',
    meaningTamil: 'எண் 100',
    distractors: ['னூ', 'ணூ', 'லூ'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_225',
    word: 'நுழைவு',
    targetLetter: 'ந',
    difficulty: 'medium',
    meaningEnglish: 'entry',
    meaningTamil: 'உள்ளே செல்லுதல்',
    distractors: ['னு', 'ணு', 'லு'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_226',
    word: 'நிழல்',
    targetLetter: 'ந',
    difficulty: 'easy',
    meaningEnglish: 'shadow',
    meaningTamil: 'ஒளி மறைவால் தோன்றும் உருவம்',
    distractors: ['னி', 'ணி', 'லி'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_227',
    word: 'நிகழ்ச்சி',
    targetLetter: 'ந',
    difficulty: 'medium',
    meaningEnglish: 'event / program',
    meaningTamil: 'நடைபெறும் நிகழ்வு',
    distractors: ['னி', 'ணி', 'லி'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_228',
    word: 'நினைவகம்',
    targetLetter: 'ந',
    difficulty: 'medium',
    meaningEnglish: 'memory / storage',
    meaningTamil: 'சேமிப்பு இடம் / memory',
    distractors: ['னி', 'ணி', 'லி'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_229',
    word: 'பந்து',
    targetLetter: 'ந',
    difficulty: 'easy',
    meaningEnglish: 'ball',
    meaningTamil: 'விளையாட்டு உருண்டை',
    distractors: ['ன்', 'ண்', 'ல்'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_230',
    word: 'வந்து',
    targetLetter: 'ந',
    difficulty: 'easy',
    meaningEnglish: 'came / having come',
    meaningTamil: 'வருதல் என்ற வினையின் வடிவம்',
    distractors: ['ன்', 'ண்', 'ல்'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_231',
    word: 'சந்தை',
    targetLetter: 'ந',
    difficulty: 'easy',
    meaningEnglish: 'market',
    meaningTamil: 'வாங்குவிற்பனை இடம்',
    distractors: ['ன்', 'ண்', 'ல்'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_232',
    word: 'சந்தனம்',
    targetLetter: 'ந',
    difficulty: 'medium',
    meaningEnglish: 'sandalwood',
    meaningTamil: 'மணமுள்ள மரப்பொருள்',
    distractors: ['ன்', 'ண்', 'ல்'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_233',
    word: 'மந்திரம்',
    targetLetter: 'ந',
    difficulty: 'medium',
    meaningEnglish: 'mantra',
    meaningTamil: 'சிறப்பு சொற்றொடர் / chant',
    distractors: ['ன்', 'ண்', 'ல்'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_234',
    word: 'இந்தியா',
    targetLetter: 'ந',
    difficulty: 'easy',
    meaningEnglish: 'India',
    meaningTamil: 'ஒரு நாடு',
    distractors: ['ன்', 'ண்', 'ல்'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_235',
    word: 'இந்த',
    targetLetter: 'ந',
    difficulty: 'easy',
    meaningEnglish: 'this',
    meaningTamil: 'அருகிலுள்ளதைச் சுட்டும் சொல்',
    distractors: ['ன்', 'ண்', 'ல்'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_236',
    word: 'அந்த',
    targetLetter: 'ந',
    difficulty: 'easy',
    meaningEnglish: 'that',
    meaningTamil: 'தொலைவில் உள்ளதைச் சுட்டும் சொல்',
    distractors: ['ன்', 'ண்', 'ல்'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_237',
    word: 'வெந்நீர்',
    targetLetter: 'ந',
    difficulty: 'easy',
    meaningEnglish: 'hot water',
    meaningTamil: 'சூடான நீர்',
    distractors: ['ன்', 'ண்', 'ல்'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_238',
    word: 'மரம்',
    targetLetter: 'ர',
    difficulty: 'easy',
    meaningEnglish: 'tree',
    meaningTamil: 'பெரிய தாவரம்',
    distractors: ['ற', 'ல', 'ள'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_239',
    word: 'வரம்',
    targetLetter: 'ர',
    difficulty: 'medium',
    meaningEnglish: 'boon',
    meaningTamil: 'கிடைத்த அருள் / சிறப்பு',
    distractors: ['ற', 'ல', 'ள'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_240',
    word: 'கரம்',
    targetLetter: 'ர',
    difficulty: 'medium',
    meaningEnglish: 'hand',
    meaningTamil: 'கை',
    distractors: ['ற', 'ல', 'ள'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_241',
    word: 'அரம்',
    targetLetter: 'ர',
    difficulty: 'hard',
    meaningEnglish: 'virtue / edge',
    meaningTamil: 'நெறி / கருவியின் கூர்மை',
    distractors: ['ற', 'ல', 'ள'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_242',
    word: 'இரக்கம்',
    targetLetter: 'ர',
    difficulty: 'medium',
    meaningEnglish: 'compassion',
    meaningTamil: 'கருணை',
    distractors: ['ற', 'ல', 'ள'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_243',
    word: 'இரவு',
    targetLetter: 'ர',
    difficulty: 'easy',
    meaningEnglish: 'night',
    meaningTamil: 'சூரியன் மறைந்த நேரம்',
    distractors: ['ற', 'ல', 'ள'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_244',
    word: 'இரண்டு',
    targetLetter: 'ர',
    difficulty: 'easy',
    meaningEnglish: 'two',
    meaningTamil: 'எண் 2',
    distractors: ['ற', 'ல', 'ள'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_245',
    word: 'இரை',
    targetLetter: 'ர',
    difficulty: 'medium',
    meaningEnglish: 'prey / food',
    meaningTamil: 'உணவு / வேட்டையாடப்படும் உயிர்',
    distractors: ['றை', 'லை', 'ளை'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_246',
    word: 'அரிசி',
    targetLetter: 'ர',
    difficulty: 'easy',
    meaningEnglish: 'rice',
    meaningTamil: 'முக்கிய தானிய உணவு',
    distractors: ['றி', 'லி', 'ளி'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_247',
    word: 'அரசு',
    targetLetter: 'ர',
    difficulty: 'easy',
    meaningEnglish: 'government',
    meaningTamil: 'ஆட்சி அமைப்பு',
    distractors: ['ற', 'ல', 'ள'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_248',
    word: 'அரசன்',
    targetLetter: 'ர',
    difficulty: 'easy',
    meaningEnglish: 'king',
    meaningTamil: 'நாட்டை ஆளும் ஆண்',
    distractors: ['ற', 'ல', 'ள'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_249',
    word: 'அருமை',
    targetLetter: 'ர',
    difficulty: 'easy',
    meaningEnglish: 'excellent / precious',
    meaningTamil: 'மிகச் சிறப்பு',
    distractors: ['று', 'லு', 'ளு'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_250',
    word: 'உரல்',
    targetLetter: 'ர',
    difficulty: 'medium',
    meaningEnglish: 'mortar',
    meaningTamil: 'இடிக்கும் பாரம்பரிய கருவி',
    distractors: ['ற', 'ல', 'ள'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_251',
    word: 'உரம்',
    targetLetter: 'ர',
    difficulty: 'easy',
    meaningEnglish: 'fertilizer',
    meaningTamil: 'செடிக்கு ஊட்டம் தரும் பொருள்',
    distractors: ['ற', 'ல', 'ள'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_252',
    word: 'உருவம்',
    targetLetter: 'ர',
    difficulty: 'easy',
    meaningEnglish: 'form / shape',
    meaningTamil: 'வடிவம்',
    distractors: ['று', 'லு', 'ளு'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_253',
    word: 'உருளை',
    targetLetter: 'ர',
    difficulty: 'medium',
    meaningEnglish: 'cylinder / rolling object',
    meaningTamil: 'உருண்ட வடிவப் பொருள்',
    distractors: ['று', 'லு', 'ளு'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_254',
    word: 'கரடி',
    targetLetter: 'ர',
    difficulty: 'easy',
    meaningEnglish: 'bear',
    meaningTamil: 'ஒரு காட்டு விலங்கு',
    distractors: ['ற', 'ல', 'ள'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_255',
    word: 'கரும்பு',
    targetLetter: 'ர',
    difficulty: 'easy',
    meaningEnglish: 'sugarcane',
    meaningTamil: 'இனிப்புச் சாறு தரும் பயிர்',
    distractors: ['று', 'லு', 'ளு'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_256',
    word: 'கருப்பு',
    targetLetter: 'ர',
    difficulty: 'easy',
    meaningEnglish: 'black',
    meaningTamil: 'ஒரு நிறம்',
    distractors: ['று', 'லு', 'ளு'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_257',
    word: 'குரங்கு',
    targetLetter: 'ர',
    difficulty: 'easy',
    meaningEnglish: 'monkey',
    meaningTamil: 'ஒரு விலங்கு',
    distractors: ['ற', 'ல', 'ள'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_258',
    word: 'குரல்',
    targetLetter: 'ர',
    difficulty: 'easy',
    meaningEnglish: 'voice',
    meaningTamil: 'பேச்சின் ஒலி',
    distractors: ['ற', 'ல', 'ள'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_259',
    word: 'குருவி',
    targetLetter: 'ர',
    difficulty: 'easy',
    meaningEnglish: 'sparrow',
    meaningTamil: 'ஒரு சிறு பறவை',
    distractors: ['று', 'லு', 'ளு'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_260',
    word: 'சரம்',
    targetLetter: 'ர',
    difficulty: 'medium',
    meaningEnglish: 'string / series',
    meaningTamil: 'தொடர் / அம்புக்கயிறு',
    distractors: ['ற', 'ல', 'ள'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_261',
    word: 'சரிவு',
    targetLetter: 'ர',
    difficulty: 'medium',
    meaningEnglish: 'slope / decline',
    meaningTamil: 'கீழ்நோக்கிய சாய்வு',
    distractors: ['றி', 'லி', 'ளி'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_262',
    word: 'தரம்',
    targetLetter: 'ர',
    difficulty: 'medium',
    meaningEnglish: 'quality / grade',
    meaningTamil: 'தகுதி / நிலை',
    distractors: ['ற', 'ல', 'ள'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_263',
    word: 'திரை',
    targetLetter: 'ர',
    difficulty: 'easy',
    meaningEnglish: 'screen / curtain',
    meaningTamil: 'மறைக்கும் துணி / screen',
    distractors: ['றை', 'லை', 'ளை'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_264',
    word: 'திருடன்',
    targetLetter: 'ர',
    difficulty: 'easy',
    meaningEnglish: 'thief',
    meaningTamil: 'திருடுபவர்',
    distractors: ['று', 'லு', 'ளு'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_265',
    word: 'பரிசு',
    targetLetter: 'ர',
    difficulty: 'easy',
    meaningEnglish: 'prize / gift',
    meaningTamil: 'வழங்கப்படும் அன்பளிப்பு',
    distractors: ['றி', 'லி', 'ளி'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_266',
    word: 'பருப்பு',
    targetLetter: 'ர',
    difficulty: 'easy',
    meaningEnglish: 'lentil',
    meaningTamil: 'ஒரு உணவுத் தானியம்',
    distractors: ['று', 'லு', 'ளு'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_267',
    word: 'பருவம்',
    targetLetter: 'ர',
    difficulty: 'medium',
    meaningEnglish: 'season / stage',
    meaningTamil: 'காலநிலைப் பகுதி / வயது நிலை',
    distractors: ['று', 'லு', 'ளு'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_268',
    word: 'மருந்து',
    targetLetter: 'ர',
    difficulty: 'easy',
    meaningEnglish: 'medicine',
    meaningTamil: 'நோய்க்கான மருந்து',
    distractors: ['று', 'லு', 'ளு'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_269',
    word: 'மரியாதை',
    targetLetter: 'ர',
    difficulty: 'medium',
    meaningEnglish: 'respect',
    meaningTamil: 'மதிப்பு காட்டுதல்',
    distractors: ['றி', 'லி', 'ளி'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_270',
    word: 'விரல்',
    targetLetter: 'ர',
    difficulty: 'easy',
    meaningEnglish: 'finger / toe',
    meaningTamil: 'கை அல்லது காலின் உறுப்பு',
    distractors: ['ற', 'ல', 'ள'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_271',
    word: 'விருது',
    targetLetter: 'ர',
    difficulty: 'easy',
    meaningEnglish: 'award',
    meaningTamil: 'சாதனைக்கான பரிசு',
    distractors: ['று', 'லு', 'ளு'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_272',
    word: 'விரைவு',
    targetLetter: 'ர',
    difficulty: 'easy',
    meaningEnglish: 'speed',
    meaningTamil: 'வேகம்',
    distractors: ['றை', 'லை', 'ளை'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_273',
    word: 'பெருமை',
    targetLetter: 'ர',
    difficulty: 'easy',
    meaningEnglish: 'pride / greatness',
    meaningTamil: 'மிகுந்த மதிப்பு',
    distractors: ['று', 'லு', 'ளு'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_274',
    word: 'திருமணம்',
    targetLetter: 'ர',
    difficulty: 'easy',
    meaningEnglish: 'marriage',
    meaningTamil: 'மணவிழா',
    distractors: ['று', 'லு', 'ளு'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_275',
    word: 'திருக்குறள்',
    targetLetter: 'ர',
    difficulty: 'medium',
    meaningEnglish: 'Tirukkural',
    meaningTamil: 'தமிழ் அறநூல்',
    distractors: ['று', 'லு', 'ளு'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_276',
    word: 'காற்று',
    targetLetter: 'ற',
    difficulty: 'easy',
    meaningEnglish: 'air / wind',
    meaningTamil: 'நம்மைச் சூழ்ந்த வாயு',
    distractors: ['ர்', 'ல்', 'ள்'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_277',
    word: 'நேற்று',
    targetLetter: 'ற',
    difficulty: 'easy',
    meaningEnglish: 'yesterday',
    meaningTamil: 'முந்தைய நாள்',
    distractors: ['ர்', 'ல்', 'ள்'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_278',
    word: 'வெற்றி',
    targetLetter: 'ற',
    difficulty: 'easy',
    meaningEnglish: 'victory',
    meaningTamil: 'சாதனை / ஜயம்',
    distractors: ['ர்', 'ல்', 'ள்'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_279',
    word: 'பற்று',
    targetLetter: 'ற',
    difficulty: 'medium',
    meaningEnglish: 'attachment',
    meaningTamil: 'பிடிப்பு / அன்பு',
    distractors: ['ர்', 'ல்', 'ள்'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_280',
    word: 'கற்று',
    targetLetter: 'ற',
    difficulty: 'easy',
    meaningEnglish: 'learned / learn',
    meaningTamil: 'கற்றல் என்ற வினை வடிவம்',
    distractors: ['ர்', 'ல்', 'ள்'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_281',
    word: 'சுற்று',
    targetLetter: 'ற',
    difficulty: 'easy',
    meaningEnglish: 'circle / go around',
    meaningTamil: 'சுற்றிச் செல்லுதல்',
    distractors: ['ர்', 'ல்', 'ள்'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_282',
    word: 'மாற்று',
    targetLetter: 'ற',
    difficulty: 'easy',
    meaningEnglish: 'change / replace',
    meaningTamil: 'வேறுபடுத்து / மாற்றம் செய்',
    distractors: ['ர்', 'ல்', 'ள்'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_283',
    word: 'ஏற்று',
    targetLetter: 'ற',
    difficulty: 'medium',
    meaningEnglish: 'accept / raise',
    meaningTamil: 'பெற்றுக்கொள் / மேலேற்று',
    distractors: ['ர்', 'ல்', 'ள்'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_284',
    word: 'தோற்று',
    targetLetter: 'ற',
    difficulty: 'medium',
    meaningEnglish: 'lose / be defeated',
    meaningTamil: 'தோல்வியடை',
    distractors: ['ர்', 'ல்', 'ள்'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_285',
    word: 'ஊற்று',
    targetLetter: 'ற',
    difficulty: 'easy',
    meaningEnglish: 'spring / pour',
    meaningTamil: 'நீர் பீறும் இடம்',
    distractors: ['ர்', 'ல்', 'ள்'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_286',
    word: 'நாற்று',
    targetLetter: 'ற',
    difficulty: 'medium',
    meaningEnglish: 'seedling',
    meaningTamil: 'நடுவதற்கான இளம் செடி',
    distractors: ['ர்', 'ல்', 'ள்'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_287',
    word: 'சேற்று',
    targetLetter: 'ற',
    difficulty: 'medium',
    meaningEnglish: 'muddy',
    meaningTamil: 'சேறு நிறைந்த',
    distractors: ['ர்', 'ல்', 'ள்'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_288',
    word: 'கீற்று',
    targetLetter: 'ற',
    difficulty: 'medium',
    meaningEnglish: 'strip / ray',
    meaningTamil: 'மெல்லிய துண்டு / கோடு',
    distractors: ['ர்', 'ல்', 'ள்'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_289',
    word: 'நூற்று',
    targetLetter: 'ற',
    difficulty: 'hard',
    meaningEnglish: 'hundred-linked form',
    meaningTamil: 'நூறு தொடர்பான இணை வடிவம்',
    distractors: ['ர்', 'ல்', 'ள்'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_290',
    word: 'அறம்',
    targetLetter: 'ற',
    difficulty: 'easy',
    meaningEnglish: 'virtue',
    meaningTamil: 'நல்லொழுக்கம்',
    distractors: ['ர', 'ல', 'ள'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_291',
    word: 'அறிவு',
    targetLetter: 'ற',
    difficulty: 'easy',
    meaningEnglish: 'knowledge',
    meaningTamil: 'தெரிந்துணரும் திறன்',
    distractors: ['ரி', 'லி', 'ளி'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_292',
    word: 'அறை',
    targetLetter: 'ற',
    difficulty: 'easy',
    meaningEnglish: 'room / slap',
    meaningTamil: 'ஒரு அறை / அடித்தல்',
    distractors: ['ரை', 'லை', 'ளை'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_293',
    word: 'அறிக்கை',
    targetLetter: 'ற',
    difficulty: 'medium',
    meaningEnglish: 'report',
    meaningTamil: 'தகவல் அறிக்கை',
    distractors: ['ரி', 'லி', 'ளி'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_294',
    word: 'அறிமுகம்',
    targetLetter: 'ற',
    difficulty: 'medium',
    meaningEnglish: 'introduction',
    meaningTamil: 'முதல் அறிதல்',
    distractors: ['ரி', 'லி', 'ளி'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_295',
    word: 'அறிவியல்',
    targetLetter: 'ற',
    difficulty: 'easy',
    meaningEnglish: 'science',
    meaningTamil: 'அறிவை ஆயும் துறை',
    distractors: ['ரி', 'லி', 'ளி'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_296',
    word: 'அறிஞர்',
    targetLetter: 'ற',
    difficulty: 'medium',
    meaningEnglish: 'scholar',
    meaningTamil: 'அறிவு மிக்கவர்',
    distractors: ['ரி', 'லி', 'ளி'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_297',
    word: 'அறுவடை',
    targetLetter: 'ற',
    difficulty: 'easy',
    meaningEnglish: 'harvest',
    meaningTamil: 'பயிர் சேகரித்தல்',
    distractors: ['ரு', 'லு', 'ளு'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_298',
    word: 'இறகு',
    targetLetter: 'ற',
    difficulty: 'easy',
    meaningEnglish: 'feather',
    meaningTamil: 'பறவையின் மென்மையான பகுதி',
    distractors: ['ர', 'ல', 'ள'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_299',
    word: 'இறுதி',
    targetLetter: 'ற',
    difficulty: 'easy',
    meaningEnglish: 'final / end',
    meaningTamil: 'கடைசி',
    distractors: ['ரு', 'லு', 'ளு'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_300',
    word: 'இறை',
    targetLetter: 'ற',
    difficulty: 'medium',
    meaningEnglish: 'God / sovereign',
    meaningTamil: 'கடவுள் / அரசன்',
    distractors: ['ரை', 'லை', 'ளை'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_301',
    word: 'இறைச்சி',
    targetLetter: 'ற',
    difficulty: 'easy',
    meaningEnglish: 'meat',
    meaningTamil: 'மாமிச உணவு',
    distractors: ['ரை', 'லை', 'ளை'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_302',
    word: 'உறவு',
    targetLetter: 'ற',
    difficulty: 'easy',
    meaningEnglish: 'relationship',
    meaningTamil: 'சொந்தம் / தொடர்பு',
    distractors: ['ர', 'ல', 'ள'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_303',
    word: 'உறுதி',
    targetLetter: 'ற',
    difficulty: 'easy',
    meaningEnglish: 'certainty / promise',
    meaningTamil: 'திடமான நிலை / வாக்குறுதி',
    distractors: ['ரு', 'லு', 'ளு'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_304',
    word: 'உறக்கம்',
    targetLetter: 'ற',
    difficulty: 'easy',
    meaningEnglish: 'sleep',
    meaningTamil: 'தூக்கம்',
    distractors: ['ர', 'ல', 'ள'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_305',
    word: 'உற்சாகம்',
    targetLetter: 'ற',
    difficulty: 'medium',
    meaningEnglish: 'enthusiasm',
    meaningTamil: 'ஆர்வமிக்க ஆற்றல்',
    distractors: ['ர்', 'ல்', 'ள்'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_306',
    word: 'குறை',
    targetLetter: 'ற',
    difficulty: 'easy',
    meaningEnglish: 'defect / shortage',
    meaningTamil: 'பற்றாக்குறை / குறைபாடு',
    distractors: ['ரை', 'லை', 'ளை'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_307',
    word: 'குறள்',
    targetLetter: 'ற',
    difficulty: 'medium',
    meaningEnglish: 'couplet',
    meaningTamil: 'குறுகிய இரடிப் பாடல்',
    distractors: ['ர', 'ல', 'ள'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_308',
    word: 'குறிப்பு',
    targetLetter: 'ற',
    difficulty: 'easy',
    meaningEnglish: 'note',
    meaningTamil: 'சிறு பதிவு',
    distractors: ['ரி', 'லி', 'ளி'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_309',
    word: 'குறிக்கோள்',
    targetLetter: 'ற',
    difficulty: 'medium',
    meaningEnglish: 'goal',
    meaningTamil: 'அடைய வேண்டிய இலக்கு',
    distractors: ['ரி', 'லி', 'ளி'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_310',
    word: 'சிறு',
    targetLetter: 'ற',
    difficulty: 'easy',
    meaningEnglish: 'small',
    meaningTamil: 'அளவில் குறைந்த',
    distractors: ['ரு', 'லு', 'ளு'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_311',
    word: 'சிறுமி',
    targetLetter: 'ற',
    difficulty: 'easy',
    meaningEnglish: 'girl',
    meaningTamil: 'பெண் குழந்தை',
    distractors: ['ரு', 'லு', 'ளு'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_312',
    word: 'திறன்',
    targetLetter: 'ற',
    difficulty: 'easy',
    meaningEnglish: 'skill / ability',
    meaningTamil: 'செய்யும் ஆற்றல்',
    distractors: ['ர', 'ல', 'ள'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_313',
    word: 'திறமை',
    targetLetter: 'ற',
    difficulty: 'easy',
    meaningEnglish: 'talent',
    meaningTamil: 'சிறந்த ஆற்றல்',
    distractors: ['ர', 'ல', 'ள'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_314',
    word: 'பிறப்பு',
    targetLetter: 'ற',
    difficulty: 'easy',
    meaningEnglish: 'birth',
    meaningTamil: 'பிறக்கும் நிகழ்வு',
    distractors: ['ர', 'ல', 'ள'],
    reviewStatus: 'generated',
    enabled: true,
  },
  {
    id: 'mayangoli_315',
    word: 'முறை',
    targetLetter: 'ற',
    difficulty: 'easy',
    meaningEnglish: 'method / turn',
    meaningTamil: 'ஒழுங்கு / வழி',
    distractors: ['ரை', 'லை', 'ளை'],
    reviewStatus: 'generated',
    enabled: true,
  },
]
