import type { RawGrammarEntry } from './wordEntry'
import rawData from './wordBank.json'

// Generated by scripts/import-grammar-workbook.ts from
// Tamizhi_Grammar_Game_2500_Word_Bank.xlsx (see wordBank.json for the actual
// 2500-entry data -- do not hand-edit either file; re-run the importer
// against a corrected workbook instead). Every row was validated at import
// time (unique id, correct_answer present in its own options, no duplicate
// options, valid category/difficulty/review_status, and a grapheme-
// segmentation smoke check on word_or_phrase) -- see the script for the
// exact rules. reviewStatus is the workbook's own vocabulary ('teacher_
// review' | 'approved'), per its README instruction to promote entries to
// 'approved' once a teacher has signed off.
//
// The cast below is a runtime-trusted assertion, not a compile-time check
// -- buildGrammarEntry (see wordEntry.ts), run on every entry at module
// load, is what actually catches a malformed row.
export const GRAMMAR_ENTRIES = rawData as RawGrammarEntry[]
