// Structured content generated by /api/generate-worksheet, persisted as-is
// in sms_teacher_worksheets.content (JSONB) -- see supabase/migrations/
// 052_teacher_worksheets.sql / 053_worksheet_content_v2.sql. Two distinct
// worksheet types, each with its own visual template
// (components/resources/PictureFillBlankWorksheet.tsx and
// ReadingComprehensionWorksheet.tsx) -- not one generic renderer, since
// the two are genuinely different exercises (phonics/vocabulary grid vs.
// passage + comprehension + glossary).
export type WorksheetType = 'picture_fillblank' | 'reading_comprehension'

export interface PictureFillBlankItem {
  word: string
  blankedWord: string
  missingLetter: string
  // Resolved server-side via lib/tamilVocabEmoji.ts -- never trust the
  // LLM to emit a correct emoji itself.
  emoji: string
}

export interface WorksheetContent {
  worksheetType: WorksheetType
  title: string
  // TYPE B only -- '' for picture_fillblank.
  passage: string
  // TYPE A only -- [] for reading_comprehension.
  items: PictureFillBlankItem[]
  // TYPE B only -- [] for picture_fillblank.
  questions: string[]
  vocabulary: { term: string; definition: string }[]
}

function isVocabEntry(value: unknown): value is { term: string; definition: string } {
  if (!value || typeof value !== 'object') return false
  const v = value as Record<string, unknown>
  return typeof v.term === 'string' && typeof v.definition === 'string'
}

function isPictureFillBlankItem(value: unknown): value is PictureFillBlankItem {
  if (!value || typeof value !== 'object') return false
  const v = value as Record<string, unknown>
  return (
    typeof v.word === 'string' &&
    typeof v.blankedWord === 'string' &&
    typeof v.missingLetter === 'string' &&
    typeof v.emoji === 'string'
  )
}

// Shared shape/discriminated-union checks common to both the raw LLM
// response and the final persisted WorksheetContent -- everything except
// each picture_fillblank item's `emoji`, which only exists after the
// generation route resolves it server-side (see emojiForWord in
// lib/tamilVocabEmoji.ts). Parameterized on the item validator so the two
// exported checks below can differ only in that one field.
function isWorksheetShape(
  value: unknown,
  isItem: (item: unknown) => boolean
): value is { worksheetType: WorksheetType; title: string; passage: string; items: unknown[]; questions: string[]; vocabulary: { term: string; definition: string }[] } {
  if (!value || typeof value !== 'object') return false
  const v = value as Record<string, unknown>

  if (typeof v.title !== 'string') return false
  if (typeof v.passage !== 'string') return false
  if (!Array.isArray(v.items) || !v.items.every(isItem)) return false
  if (!Array.isArray(v.questions) || !v.questions.every((q) => typeof q === 'string')) return false
  if (!Array.isArray(v.vocabulary) || !v.vocabulary.every(isVocabEntry)) return false

  if (v.worksheetType === 'picture_fillblank') {
    return v.items.length > 0
  }
  if (v.worksheetType === 'reading_comprehension') {
    return v.passage.trim().length > 0 && v.questions.length > 0
  }
  return false
}

// Validates the raw shape returned by the LLM, which for
// picture_fillblank items is ONLY a chosen `word` -- blankedWord/
// missingLetter/emoji are all computed deterministically server-side
// afterward (see blankOutOneLetter in lib/tamilVocabEmoji.ts; asking the
// LLM to blank a Tamil word itself was tried and produced nonsense, since
// Tamil consonant+vowel-sign combinations are multi-codepoint grapheme
// clusters the model doesn't reliably split/rejoin). Use this in the
// generation route only; use isWorksheetContent everywhere else
// (save/assign), once the full item has been resolved.
export function isRawWorksheetContent(value: unknown): value is Omit<WorksheetContent, 'items'> & {
  items: { word: string }[]
} {
  return isWorksheetShape(value, (item) => {
    if (!item || typeof item !== 'object') return false
    return typeof (item as Record<string, unknown>).word === 'string'
  })
}

// Narrow, defensive shape-check on a FINAL, fully-formed worksheet (i.e.
// after emoji resolution) -- used by the save/assign routes, which
// receive their payload from the client after generation completed.
export function isWorksheetContent(value: unknown): value is WorksheetContent {
  return isWorksheetShape(value, isPictureFillBlankItem)
}

// Renders structured worksheet content into plain text for an assignment
// description -- students see assignment descriptions as plain text (see
// app/student/assignments/[id]/page.tsx), so there's no rich-content
// rendering path to reuse here.
export function renderWorksheetAsPlainText(content: WorksheetContent): string {
  const lines: string[] = [content.title, '']

  if (content.worksheetType === 'picture_fillblank') {
    lines.push('Fill in the missing letter:')
    content.items.forEach(({ blankedWord, missingLetter }) => lines.push(`${blankedWord}  (answer: ${missingLetter})`))
    return lines.join('\n').trim()
  }

  lines.push(content.passage, '')

  if (content.questions.length > 0) {
    lines.push('Questions:')
    content.questions.forEach((q, i) => lines.push(`${i + 1}. ${q}`))
    lines.push('')
  }

  if (content.vocabulary.length > 0) {
    lines.push('Vocabulary:')
    content.vocabulary.forEach(({ term, definition }) => lines.push(`${term} - ${definition}`))
  }

  return lines.join('\n').trim()
}
