// Structured content generated by /api/generate-worksheet, persisted as-is
// in sms_teacher_worksheets.content (JSONB) -- see supabase/migrations/
// 052_teacher_worksheets.sql / 053_worksheet_content_v2.sql. Two distinct
// worksheet types, each with its own visual template
// (components/resources/PictureFillBlankWorksheet.tsx and
// ReadingComprehensionWorksheet.tsx) -- not one generic renderer, since
// the two are genuinely different exercises (phonics/vocabulary grid vs.
// passage + comprehension + glossary).
export type WorksheetType = 'picture_fillblank' | 'reading_comprehension'

export interface PictureFillBlankItem {
  word: string
  blankedWord: string
  missingLetter: string
  // Resolved server-side via lib/tamilVocabEmoji.ts -- never trust the
  // LLM to emit a correct emoji itself.
  emoji: string
}

export interface WorksheetContent {
  worksheetType: WorksheetType
  title: string
  // TYPE B only -- '' for picture_fillblank.
  passage: string
  // TYPE A only -- [] for reading_comprehension.
  items: PictureFillBlankItem[]
  // TYPE B only -- [] for picture_fillblank.
  questions: string[]
  vocabulary: { term: string; definition: string }[]
}

function isPictureFillBlankItem(value: unknown): value is PictureFillBlankItem {
  if (!value || typeof value !== 'object') return false
  const v = value as Record<string, unknown>
  return (
    typeof v.word === 'string' &&
    typeof v.blankedWord === 'string' &&
    typeof v.missingLetter === 'string' &&
    typeof v.emoji === 'string'
  )
}

function isVocabEntry(value: unknown): value is { term: string; definition: string } {
  if (!value || typeof value !== 'object') return false
  const v = value as Record<string, unknown>
  return typeof v.term === 'string' && typeof v.definition === 'string'
}

// Narrow, defensive shape-check on parsed JSON from the LLM -- a
// reasoning-model provider (Sarvam/Groq) can still wrap its answer in
// prose or omit a field despite explicit instructions not to, so this is
// checked before the content is ever persisted or shown to a teacher.
// Validates the discriminated union: each type requires its own fields
// to be meaningfully populated, not just present as empty arrays.
export function isWorksheetContent(value: unknown): value is WorksheetContent {
  if (!value || typeof value !== 'object') return false
  const v = value as Record<string, unknown>

  if (typeof v.title !== 'string') return false
  if (typeof v.passage !== 'string') return false
  if (!Array.isArray(v.items) || !v.items.every(isPictureFillBlankItem)) return false
  if (!Array.isArray(v.questions) || !v.questions.every((q) => typeof q === 'string')) return false
  if (!Array.isArray(v.vocabulary) || !v.vocabulary.every(isVocabEntry)) return false

  if (v.worksheetType === 'picture_fillblank') {
    return v.items.length > 0
  }
  if (v.worksheetType === 'reading_comprehension') {
    return v.passage.trim().length > 0 && v.questions.length > 0
  }
  return false
}

// Renders structured worksheet content into plain text for an assignment
// description -- students see assignment descriptions as plain text (see
// app/student/assignments/[id]/page.tsx), so there's no rich-content
// rendering path to reuse here.
export function renderWorksheetAsPlainText(content: WorksheetContent): string {
  const lines: string[] = [content.title, '']

  if (content.worksheetType === 'picture_fillblank') {
    lines.push('Fill in the missing letter:')
    content.items.forEach(({ blankedWord, missingLetter }) => lines.push(`${blankedWord}  (answer: ${missingLetter})`))
    return lines.join('\n').trim()
  }

  lines.push(content.passage, '')

  if (content.questions.length > 0) {
    lines.push('Questions:')
    content.questions.forEach((q, i) => lines.push(`${i + 1}. ${q}`))
    lines.push('')
  }

  if (content.vocabulary.length > 0) {
    lines.push('Vocabulary:')
    content.vocabulary.forEach(({ term, definition }) => lines.push(`${term} - ${definition}`))
  }

  return lines.join('\n').trim()
}
