// Structured content generated by /api/generate-worksheet, persisted as-is
// in sms_teacher_worksheets.content (JSONB) -- see supabase/migrations/
// 052_teacher_worksheets.sql. One shape shared by the generation route,
// the save/list API, and the client UI so all three stay in sync.
export interface WorksheetContent {
  passage: string
  comprehensionQuestions: string[]
  vocabulary: { word: string; meaning: string }[]
  wordPuzzle: { word: string; scrambled: string }[]
}

// Narrow, defensive shape-check on parsed JSON from the LLM -- a
// reasoning-model provider (Sarvam/Groq) can still wrap its answer in
// prose or omit a field despite explicit instructions not to, so this is
// checked before the content is ever persisted or shown to a teacher.
export function isWorksheetContent(value: unknown): value is WorksheetContent {
  if (!value || typeof value !== 'object') return false
  const v = value as Record<string, unknown>
  return (
    typeof v.passage === 'string' &&
    Array.isArray(v.comprehensionQuestions) &&
    v.comprehensionQuestions.every((q) => typeof q === 'string') &&
    Array.isArray(v.vocabulary) &&
    v.vocabulary.every((item) => item && typeof item === 'object' && typeof (item as { word: unknown }).word === 'string' && typeof (item as { meaning: unknown }).meaning === 'string') &&
    Array.isArray(v.wordPuzzle) &&
    v.wordPuzzle.every((item) => item && typeof item === 'object' && typeof (item as { word: unknown }).word === 'string' && typeof (item as { scrambled: unknown }).scrambled === 'string')
  )
}

// Renders structured worksheet content into plain text for an assignment
// description -- students see assignment descriptions as plain text (see
// app/student/assignments/[id]/page.tsx), so there's no rich-content
// rendering path to reuse here.
export function renderWorksheetAsPlainText(content: WorksheetContent): string {
  const lines: string[] = [content.passage, '']

  if (content.comprehensionQuestions.length > 0) {
    lines.push('Questions:')
    content.comprehensionQuestions.forEach((q, i) => lines.push(`${i + 1}. ${q}`))
    lines.push('')
  }

  if (content.vocabulary.length > 0) {
    lines.push('Vocabulary:')
    content.vocabulary.forEach(({ word, meaning }) => lines.push(`${word} - ${meaning}`))
    lines.push('')
  }

  if (content.wordPuzzle.length > 0) {
    lines.push('Word Puzzle:')
    content.wordPuzzle.forEach(({ scrambled }) => lines.push(scrambled))
  }

  return lines.join('\n').trim()
}
